### ISSUE TITLE
Missing Item Template

### ISSUE THREAD

**Issue by paul1956** [RandomlyKnighted/MSDN-SideWaffle-Projects#3]
I am trying to follow the instructions in the article but I don't see the Item Template listed under extensibility in VS 2013 Ultimate.
![capture](https://cloud.githubusercontent.com/assets/12789369/8026678/b6855572-0d35-11e5-90c0-6183b5a5d858.JPG)

**Comment by RandomlyKnighted** [comment]
Hi @paul1956 thanks for reading the article. 

@sayedihashimi can you think of any reason why only a portion of the item template would show up in Visual Studio? From the screenshot it looks like there are nine item templates missing.

**Comment by paul1956** [comment]
I am using VB if that matters.

**Comment by RandomlyKnighted** [comment]
Ah, yes that would make a difference. The item template you're looking for is only set up for C# projects. I'm going to create an issue about this in the [SideWaffle issues page](https://github.com/ligershark/side-waffle/issues) so we can get that fixed.

**Comment by RandomlyKnighted** [comment]
You can track the issue [here](https://github.com/ligershark/side-waffle/issues/276).

**Comment by paul1956** [comment]
I created a C# Project, added the  Item Template, copied the files to my VB project, then followed the instructions in the article. When I run the project <ctrl> F5. I get the error below. Did I miss something by just copying the files? Do I need to wait until the bug is fixed? Since I don’t actually write any code, is there any reason not to just use the C# project but include my VB module?

 

Exception Type       : Microsoft.VisualStudio.ExtensionManager.NotInstalledException

Exception Message    : Exception of type 'Microsoft.VisualStudio.ExtensionManager.NotInstalledException' was thrown.

Exception Stack Trace:    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.GetInstalledExtension(String identifier)

   at MadsKristensen.EditorExtensions.CompatibilityChecker.get_WebEssentialsVersionString()

   at MadsKristensen.EditorExtensions.CompatibilityChecker.<StartCheckingCompatibility>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MadsKristensen.EditorExtensions.CompatibilityCheckerPackage.<Initialize>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Exception Data:

Key: System.Object, Value: [null]

**Comment by RandomlyKnighted** [comment]
When you copied the two Visual Basic files did you rename them so that they end with an e instead of a -?

I hope to have a fix released either tonight or tomorrow so that you can add the item template in VB projects.

**Comment by paul1956** [comment]
I renamed on. I am not using Web template for testing.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by RandomlyKnighted** [comment]
Can you please provide me with a screenshot of your Solution Explorer window.

**Comment by paul1956** [comment]
The one I faked using files copied from C#?

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by RandomlyKnighted** [comment]
Yes.

**Comment by RandomlyKnighted** [comment]
@paul1956 try installing this [version of SideWaffle](https://ci.appveyor.com/api/buildjobs/chmlpa32lm16107x/artifacts/TemplatePack.vsix) and see if it works for you. It contains the fix I've made allowing those templates to show up for VB projects. 

I have tested it on my end and it looks good. I'm just waiting on it to officially be approved and released.

**Comment by paul1956** [comment]
I installed the update, the Add New item Dialog lists 6 items.



 

I added the Item Template, made changes listed in article.



 

I set source.extension.vsixmanifest BuildAction property to “None”

 

But still get this error.

 

Exception Type       : Microsoft.VisualStudio.ExtensionManager.NotInstalledException

Exception Message    : Exception of type 'Microsoft.VisualStudio.ExtensionManager.NotInstalledException' was thrown.

Exception Stack Trace:    at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.GetInstalledExtension(String identifier)

   at MadsKristensen.EditorExtensions.CompatibilityChecker.get_WebEssentialsVersionString()

   at MadsKristensen.EditorExtensions.CompatibilityChecker.<StartCheckingCompatibility>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MadsKristensen.EditorExtensions.CompatibilityCheckerPackage.<Initialize>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Exception Data:

Key: System.Object, Value: [null]

**Comment by RandomlyKnighted** [comment]
Could you zip up the project files and share them here? I'd like to take a look at the project and see if I can figure out it out as I'm unable to replicate this on my machine.

**Comment by RandomlyKnighted** [comment]
Did you mean to put something in your post?

**Comment by paul1956** [comment]
I put the zip file and 3 pictures

**Comment by RandomlyKnighted** [comment]
The zip file and pictures didn't show up. Can you share it via OneDrive, Dropbox, Google Drive, or whatever you use?

**Comment by paul1956** [comment]
https://onedrive.live.com/redir?resid=5bf2f69e9b9fa722!12147 <https://onedrive.live.com/redir?resid=5bf2f69e9b9fa722!12147&authkey=!ABsGkwavWqqBRco&ithint=file%2czip> &authkey=!ABsGkwavWqqBRco&ithint=file%2czip

**Comment by RandomlyKnighted** [comment]
I had no issues creating the extension. I built the solution, installed the VSIX file located in the Release folder. After restarting Visual Studio, the templates showed up in the Add New Item dialog.

After looking over that error again, it looks like the issue relates to Web Essentials. Have you tried disabling the extension before trying to build and install the template?

**Comment by paul1956** [comment]
I ran it using the <Carl>F5.

I will try your way and also removing Web Essentials.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by paul1956** [comment]
If I build and install instead of using <Crtl> F5 it works as expected. Thanks it will be very useful.

**Comment by RandomlyKnighted** [comment]
You're welcome. I'm going to go ahead and close this issue. You're welcome to reopen it if you have similar issues in the future.

Also I'd suggest creating an [issue on the Web Essentials repo page](https://github.com/madskristensen/WebEssentials2013/issues) explaining the issues you were having. Someone there should be able to help you get that sorted out.

**Comment by paul1956** [comment]
I don’t know if this is a new bug, feature or expected behavior but when I do “Add New Item” under “common items/code”, I see my two items Module1 and Class1. But I also see a new folder “My Custom Extensions” and under that folder I also see Module1 and Class1.

 

Is that as expected?

**Comment by RandomlyKnighted** [comment]
I noticed that as well. @sayedihashimi can probably answer that question better than I can.
